### ISSUE TITLE
Add pushnix to nixpkgs

### ISSUE THREAD

**Issue by pinage404** [arnarg/pushnix#3]
Please add `pushnix` to the [`nixpkgs`](https://github.com/NixOS/nixpkgs) repository or provide an alternative way to let Nix handle it

I would like to be able to use `pushnix` without the need to clone the repository then run a command to build it (`make`) then add it to my `$PATH`

I would like to be able to add `pushnix` in `environment.systemPackages` into my `/etc/nixos/configuration.nix`

**Comment by pinage404** [comment]
I found what i was looking for !

You already did it :smiley: 

https://github.com/arnarg/config/commit/76322ba1a088991d60845300246566ba9ccaa43b

**Comment by rapenne-s** [comment]
@pinage404 this wasn't a commit into `nixpkgs`

**Comment by pinage404** [comment]
I was looking for a way

> to be able to use `pushnix` without the need to clone the repository then run a command to build it (`make`) then add it to my `$PATH`
> 
> I would like to be able to add `pushnix` in `environment.systemPackages` into my `/etc/nixos/configuration.nix`

With the commit above, i am able to simple [add pushnix to my configuration](https://gitlab.com/pinage404/dotfiles/-/blob/f21c840e337ba8fa6c0efdacbebf26d4d5f1d2d5/nixpkgs/package/cli/nix.nix#L37)

---

The creator don't use this project anymore

https://github.com/arnarg/pushnix/issues/4#issuecomment-821799127

He switched to Nix Flake

https://github.com/arnarg/pushnix/issues/4#issuecomment-821805927

---

Maybe you can open a PR to add it to nixpkgs ?
